### ISSUE TITLE
How do you cope with distros having requiretty enabled in /etc/sudoers

### ISSUE THREAD

**Issue by rubiojr** [delano/rye#24]
Hey Delano,

Having issues with:

```
box = Rye::Box.new host, args
box.sudo 'my-foo-command'
```

or

```
box = Rye::Box.new host, args
box.enable_sudo
box.execute 'my-bar-command'  
```

when /etc/sudoers has "Defaults    requiretty" (like CentOS):

```
/home/rubiojr/.rvm/gems/ruby-1.9.3-p194/gems/rye-0.9.7/lib/rye/box.rb:855:in `rescue in run_command': sudo: sorry, you must have a tty to run sudo (cmd: sudo cat /etc/issue; status: 1) (Rye::Err)
    from /home/rubiojr/.rvm/gems/ruby-1.9.3-p194/gems/rye-0.9.7/lib/rye/box.rb:806:in `run_command'
    from /home/rubiojr/.rvm/gems/ruby-1.9.3-p194/gems/rye-0.9.7/lib/rye/box.rb:597:in `sudo'
        ...
```

Haven't been able to find a good way to cope with this without patching. Any hints?

**Comment by ms-ati** [comment]
If you are using an Amazon linux AMI that supports user data, it's probably best to just change the sudoers config like this: https://github.com/mitchellh/vagrant/issues/1482#issuecomment-17444459
